[package]
name = "cutegdb-core"
version.workspace = true
edition.workspace = true

[dependencies]
cutegdb-mi = { path = "../mi" }
tokio.workspace = true
thiserror.workspace = true
capstone = "0.14"
object = { version = "0.40", default-features = false, features = ["read_core", "elf", "std"] }
nix = { version = "0.31", features = ["term", "fs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
